spring.application.name=dailywage-connect

spring.datasource.url=jdbc:mysql://acela.proxy.rlwy.net:28383/railway
spring.datasource.username=root
spring.datasource.password=hOqgrARcpwtQtdYosbHIzyZgoHLDMJqX

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=${PORT:8080}
spring.h2.console.enabled=false